# Generated by Django 5.2.8 on 2025-12-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_up', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
